-- MySQL Script generated by MySQL Workbench
-- Fri Dec 23 10:26:08 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vendedores
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vendedores
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vendedores` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `vendedores` ;

-- -----------------------------------------------------
-- Table `vendedores`.`ven_cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendedores`.`ven_cargo` (
  `idCargo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(150) NULL COMMENT '',
  `estado` ENUM('A', 'I') NULL DEFAULT 'A' COMMENT '',
  `fechaMod` DATETIME NULL COMMENT '',
  `fecha` DATETIME NULL COMMENT '',
  PRIMARY KEY (`idCargo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendedores`.`ven_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendedores`.`ven_usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idCargo` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(150) NULL COMMENT '',
  `apellido` VARCHAR(150) NULL COMMENT '',
  `email` VARCHAR(75) NULL COMMENT '',
  `usuario` VARCHAR(75) NULL COMMENT '',
  `contrasena` VARCHAR(75) NULL COMMENT '',
  `puntos` VARCHAR(10) NULL COMMENT '',
  `estado` ENUM('A', 'I') NULL DEFAULT 'A' COMMENT '',
  `fechaMod` DATETIME NULL COMMENT '',
  `fecha` DATETIME NULL COMMENT '',
  PRIMARY KEY (`idUsuario`)  COMMENT '',
  INDEX `fk_ven_usuario_ven_cargo1_idx` (`idCargo` ASC)  COMMENT '',
  CONSTRAINT `fk_ven_usuario_ven_cargo1`
    FOREIGN KEY (`idCargo`)
    REFERENCES `vendedores`.`ven_cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendedores`.`ven_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendedores`.`ven_categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(150) NULL COMMENT '',
  `imagen` VARCHAR(150) NULL COMMENT '',
  `idPadre` INT NULL COMMENT '',
  `estado` ENUM('A', 'I') NULL DEFAULT 'A' COMMENT '',
  `fechaMod` DATETIME NULL COMMENT '',
  `fecha` DATETIME NULL COMMENT '',
  PRIMARY KEY (`idCategoria`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendedores`.`ven_usuario_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendedores`.`ven_usuario_admin` (
  `idUsuarioAdmin` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(150) NULL COMMENT '',
  `apellido` VARCHAR(150) NULL COMMENT '',
  `email` VARCHAR(75) NULL COMMENT '',
  `usuario` VARCHAR(75) NULL COMMENT '',
  `contrasena` VARCHAR(75) NULL COMMENT '',
  `estado` ENUM('A', 'I') NULL DEFAULT 'A' COMMENT '',
  `fechaMod` DATETIME NULL COMMENT '',
  `fecha` DATETIME NULL COMMENT '',
  PRIMARY KEY (`idUsuarioAdmin`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendedores`.`ven_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendedores`.`ven_producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(75) NULL COMMENT '',
  `estado` ENUM('A', 'I') NULL DEFAULT 'A' COMMENT '',
  `fechaMod` DATETIME NULL COMMENT '',
  `fecha` DATETIME NULL COMMENT '',
  PRIMARY KEY (`idProducto`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendedores`.`ven_noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendedores`.`ven_noticia` (
  `idNoticia` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idCategoria` INT NOT NULL COMMENT '',
  `idUsuarioAdmin` INT NOT NULL COMMENT '',
  `idProducto` INT NOT NULL COMMENT '',
  `titulo` VARCHAR(150) NULL COMMENT '',
  `subtitulo` VARCHAR(150) NULL COMMENT '',
  `imagen` VARCHAR(150) NULL COMMENT '',
  `video` VARCHAR(150) NULL COMMENT '',
  `pdf` VARCHAR(150) NULL COMMENT '',
  `contenido` TEXT NULL COMMENT '',
  `tipoTemplate` INT NULL COMMENT '',
  `fechaDesde` DATETIME NULL COMMENT '',
  `fechaHasta` DATETIME NULL COMMENT '',
  `estado` ENUM('A', 'I') NULL DEFAULT 'A' COMMENT '',
  `fechaMod` DATETIME NULL COMMENT '',
  `fecha` DATETIME NULL COMMENT '',
  PRIMARY KEY (`idNoticia`)  COMMENT '',
  INDEX `fk_noticia_categoria_idx` (`idCategoria` ASC)  COMMENT '',
  INDEX `fk_noticia_usuario_admin1_idx` (`idUsuarioAdmin` ASC)  COMMENT '',
  INDEX `fk_ven_noticia_ven_producto1_idx` (`idProducto` ASC)  COMMENT '',
  CONSTRAINT `fk_noticia_categoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `vendedores`.`ven_categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_noticia_usuario_admin1`
    FOREIGN KEY (`idUsuarioAdmin`)
    REFERENCES `vendedores`.`ven_usuario_admin` (`idUsuarioAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ven_noticia_ven_producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `vendedores`.`ven_producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendedores`.`ven_seccion_noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendedores`.`ven_seccion_noticia` (
  `idSeccionNoticia` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idNoticia` INT NOT NULL COMMENT '',
  `titulo` VARCHAR(150) NULL COMMENT '',
  `imagen` VARCHAR(150) NULL COMMENT '',
  `contenido` TEXT NULL COMMENT '',
  `estado` ENUM('A', 'I') NULL DEFAULT 'A' COMMENT '',
  `fechaMod` DATETIME NULL COMMENT '',
  `fecha` DATETIME NULL COMMENT '',
  PRIMARY KEY (`idSeccionNoticia`)  COMMENT '',
  INDEX `fk_ven_seccion_noticia_ven_noticia1_idx` (`idNoticia` ASC)  COMMENT '',
  CONSTRAINT `fk_ven_seccion_noticia_ven_noticia1`
    FOREIGN KEY (`idNoticia`)
    REFERENCES `vendedores`.`ven_noticia` (`idNoticia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `vendedores`.`ven_cargo`
-- -----------------------------------------------------
START TRANSACTION;
USE `vendedores`;
INSERT INTO `vendedores`.`ven_cargo` (`idCargo`, `nombre`, `estado`, `fechaMod`, `fecha`) VALUES (1, 'Desarrollador', 'A', '2016-12-23 09:57:02', '2016-12-23 09:57:02');

COMMIT;


-- -----------------------------------------------------
-- Data for table `vendedores`.`ven_categoria`
-- -----------------------------------------------------
START TRANSACTION;
USE `vendedores`;
INSERT INTO `vendedores`.`ven_categoria` (`idCategoria`, `nombre`, `imagen`, `idPadre`, `estado`, `fechaMod`, `fecha`) VALUES (DEFAULT, 'Ventas', NULL, 0, 'A', '2016-12-23 09:57:02', '2016-12-23 09:57:02');
INSERT INTO `vendedores`.`ven_categoria` (`idCategoria`, `nombre`, `imagen`, `idPadre`, `estado`, `fechaMod`, `fecha`) VALUES (DEFAULT, 'Marketing', NULL, 0, 'A', '2016-12-23 09:57:02', '2016-12-23 09:57:02');

COMMIT;


-- -----------------------------------------------------
-- Data for table `vendedores`.`ven_usuario_admin`
-- -----------------------------------------------------
START TRANSACTION;
USE `vendedores`;
INSERT INTO `vendedores`.`ven_usuario_admin` (`idUsuarioAdmin`, `nombre`, `apellido`, `email`, `usuario`, `contrasena`, `estado`, `fechaMod`, `fecha`) VALUES (1, 'Julian', 'Barrera', 'julian.barrera@a3bpo.co', 'julian.barrera', '123456', 'A', '2016-12-23 09:57:02', '2016-12-23 09:57:02');
INSERT INTO `vendedores`.`ven_usuario_admin` (`idUsuarioAdmin`, `nombre`, `apellido`, `email`, `usuario`, `contrasena`, `estado`, `fechaMod`, `fecha`) VALUES (2, 'Luis', 'Cruz', 'luis.cruz@brm.com.co', 'luis.cruz@brm.com.co', '4dm1nVendedores', 'A', '2016-12-23 09:57:02', '2016-12-23 09:57:02');

COMMIT;

