<?php
require("./".$prefijo."db/db.venCargo.php");
require("./".$prefijo."db/db.venCategoria.php");
require("./".$prefijo."db/db.venNoticia.php");
require("./".$prefijo."db/db.venSeccionNoticia.php");
require("./".$prefijo."db/db.venUsuario.php");
require("./".$prefijo."db/db.venUsuarioAdmin.php");
require("./".$prefijo."db/db.venProducto.php");
?>